feature_names:
csv_prefix_to_strip: /gpfs/gibbs/project/quinn/ms3682/raw_data
csv_prefix_to_add: /Users/malcolm/output/chord_tones_datasets
column_types:
  inversion: float
make_piano_rolls: false
make_score_pdfs: true
